INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:27:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:27:55] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Çìºê¾î\Desktop\virus_model_site\app.py", line 128, in upload_file
    writer.writerow(result)
NameError: name 'result' is not defined
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:28:25] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Çìºê¾î\Desktop\virus_model_site\app.py", line 128, in upload_file
    writer.writerow(features)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
ValueError: I/O operation on closed file.
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:29:21] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Çìºê¾î\Desktop\virus_model_site\app.py", line 128, in upload_file
    writer.writerow(features)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
ValueError: I/O operation on closed file.
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:30:20] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Çìºê¾î\Desktop\virus_model_site\app.py", line 127, in upload_file
    writer.writeheader()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\csv.py", line 143, in writeheader
    return self.writerow(header)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
ValueError: I/O operation on closed file.
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:31:26] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Çìºê¾î\Desktop\virus_model_site\app.py", line 127, in upload_file
    writer.writeheader()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\csv.py", line 143, in writeheader
    return self.writerow(header)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
ValueError: I/O operation on closed file.
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:32:07] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:34:18] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:47:26] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:52:54] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:57:19] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 20:58:49] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:05:01] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
DEBUG:matplotlib:matplotlib data path: C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\Çìºê¾î\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:09:30] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:12:38] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Çìºê¾î\Desktop\virus_model_site\app.py", line 135, in upload_file
    file.save(file_path)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\datastructures\file_storage.py", line 125, in save
    dst = open(dst, "wb")
OSError: [Errno 22] Invalid argument: 'uploads\\register.exe'
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:12:50] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Çìºê¾î\Desktop\virus_model_site\app.py", line 144, in upload_file
    writer.writerow(features)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\csv.py", line 147, in _dict_to_list
    wrong_fields = rowdict.keys() - self.fieldnames
AttributeError: 'NoneType' object has no attribute 'keys'
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:12:52] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
DEBUG:matplotlib:matplotlib data path: C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\Çìºê¾î\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Çìºê¾î\Desktop\virus_model_site\app.py", line 148, in upload_file
    a = model()
  File "C:\Users\Çìºê¾î\Desktop\virus_model_site\app.py", line 100, in model
    result_float = model.predict_proba(df)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\lightgbm\sklearn.py", line 1335, in predict_proba
    result = super().predict(
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\lightgbm\sklearn.py", line 1035, in predict
    return self._Booster.predict(  # type: ignore[union-attr]
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\lightgbm\basic.py", line 4738, in predict
    return predictor.predict(
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\lightgbm\basic.py", line 1137, in predict
    data = _data_from_pandas(
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\lightgbm\basic.py", line 846, in _data_from_pandas
    _pandas_to_numpy(data, target_dtype=target_dtype),
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\lightgbm\basic.py", line 792, in _pandas_to_numpy
    _check_for_bad_pandas_dtypes(data.dtypes)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\lightgbm\basic.py", line 782, in _check_for_bad_pandas_dtypes
    raise ValueError(
ValueError: pandas dtypes must be int, float or bool.
Fields with bad pandas dtypes: Entropy: object
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:13:23] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
DEBUG:matplotlib:matplotlib data path: C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\Çìºê¾î\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'upload_file' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:15:29] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:15:52] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:15:53] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:16:12] "GET / HTTP/1.1" 200 -
DEBUG:matplotlib:matplotlib data path: C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\Çìºê¾î\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'upload_file' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:16:33] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:18:26] "GET / HTTP/1.1" 200 -
DEBUG:matplotlib:matplotlib data path: C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\Çìºê¾î\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:18:50] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:20:39] "GET / HTTP/1.1" 200 -
DEBUG:matplotlib:matplotlib data path: C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\Çìºê¾î\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:21:02] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:22:47] "GET / HTTP/1.1" 200 -
DEBUG:matplotlib:matplotlib data path: C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\Çìºê¾î\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:23:07] "POST /upload HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.30.1.55:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:59:54] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 21:59:54] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
DEBUG:matplotlib:matplotlib data path: C:\Users\Çìºê¾î\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\Çìºê¾î\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:werkzeug:127.0.0.1 - - [10/Jul/2024 22:19:26] "POST /upload HTTP/1.1" 200 -
